### ISSUE TITLE
Compile order file references unknown files

### ISSUE THREAD

**Issue by Paebbels** [OSVVM/AXI4#3]
`TbAxi4LIte_compile.txt` on branch `dev` references non existing files.

Please use an appropriate file extension.  
The files is an ASCII encoded data base file and not text file.

**Suggestions:**
* no extension
* `*.order`
* `*.files`

------------------
After fixing some of the dependency issues, I get this error:

![image](https://user-images.githubusercontent.com/956109/41742025-162f8df8-759d-11e8-879c-5c79e6623237.png)

**Comment by Paebbels** [comment]
Where is ToTransaction defined?

I can't find it in AXI4 nor in OSVVM 2018.04 (branch `dev`)

**Comment by JimLewis** [comment]
It is in OSVVM/ResolutionPkg - just pushed it.
